### ISSUE TITLE
Upgrade Wishlist for 2.0

### ISSUE THREAD

**Issue by DamianSuess** [SuessLabs/Plugin.BlueZ#1]
Refactoring:
* [ ] Rename `Device.GetAllAsync()` to `..GetPropertiesAsync()`
* [ ] Rename `Device.GetUUIDsAsync()` to `..GetServiceUuidsAsync()`
* [ ] Include `DeviceExtensions` as part of `Device` class
* [ ] Rename `Device.GetConnectedAsync()` to `IsConnectedAsync()`

Normalization:
* [ ] Use custom Interfaces versus BlueZ dependent ones

**Comment by animaonline** [comment]
Hi, are you planning to add support for peripherals?

**Comment by DamianSuess** [comment]
@animaonline, are you referring to HIDs such as a virtual BLE keyboard/mouse? In that case, not at this time.
Currently, this library is intended to provide your .NET app access to the BlueZ APIs.

**Comment by animaonline** [comment]
@DamianSuess no, that's not what I mean, the Bluez stack supports so called BLE peripherals, where the bluetooth stack acts as a BLE server, allowing clients to connect to it.

**Comment by DamianSuess** [comment]
@animaonline, yes, this is supported. However, the project currently does not have a sample app provided at this time.  Community contributions are always welcomed :)

This repository is being marked as Read-Only and all functionality has been ported over to, [Linux.Bluetooth](https://github.com/SuessLabs/Linux.Bluetooth)

Nonetheless, this request will be placed on the new backlog 👍  Please update your NuGet packages to, **Linux.Bluetooth**
